### ISSUE TITLE
Kanban Board capstone

### ISSUE THREAD

**Issue by KaskMIL** [KaskMIL/book-a-jet-backend#15]
[Kanban Board](https://github.com/users/KaskMIL/projects/1/views/1)
We are a team of 4 people: @masangana, @worashf, @mikemtzp and @KaskMIL.
![Captura de Pantalla 2022-10-19 a la(s) 19 54 56](https://user-images.githubusercontent.com/36968008/196819841-5d3cebb6-99a2-4bd5-86ec-81a309b914d1.png)

**Comment by Meltrust** [comment]
Hi @KaskMIL,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been filled with descriptions✔️
- Nice descriptions 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

- [x] According to the requirements, there cannot be a >= 5 points difference between 1 team member and the others.  Please, kindly correct this issue. 

## Additional help and tips

@masangana is the person with less points than the others in the team (I counted them all, twice). Just assign him to other extra task (can be a group task that already exists) so he has 2-4 points more.

Cheers and Happy coding!👏👏👏



**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

**Comment by KaskMIL** [comment]
Hi @Meltrust,
Thanks for the review!
We will implement the changes required.
Happy coding!

**Comment by Meltrust** [comment]
Hi @KaskMIL,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏



------
